INSERT INTO users (name, age) VALUES ("Anna", 10);
INSERT INTO users (name, age) VALUES ("Bobby", 11);
INSERT INTO users (name, age) VALUES ("Chad", 12);
INSERT INTO users (name, age) VALUES ("David", 13);
INSERT INTO users (name, age) VALUES ("Edward", 14);
INSERT INTO users (name, age) VALUES ("Frank", 15);
INSERT INTO users (name, age) VALUES ("Gene", 16);
INSERT INTO users (name, age) VALUES ("Harry", 17);
INSERT INTO users (name, age) VALUES ("Ingrid", 18);
INSERT INTO users (name, age) VALUES ("Joe", 19);
INSERT INTO users (name, age) VALUES ("Kevin", 20);
INSERT INTO users (name, age) VALUES ("Lorry", 21);
INSERT INTO users (name, age) VALUES ("Mindy", 22);
INSERT INTO users (name, age) VALUES ("Nancy", 23);
INSERT INTO users (name, age) VALUES ("Ophelia", 24);
INSERT INTO users (name, age) VALUES ("Peter", 25);
INSERT INTO users (name, age) VALUES ("Quinn", 26);
INSERT INTO users (name, age) VALUES ("Rochelle", 27);
INSERT INTO users (name, age) VALUES ("Sam", 28);
INSERT INTO users (name, age) VALUES ("Tammy", 29);

INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ( "Project1", "Category1", "10000", "06/01/2020", "06/30/2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ( "Project2", "Category2", "10000", "06/01/2020", "06/30/2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ( "Project3", "Category3", "10000", "06/01/2020", "06/30/2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ( "Project4", "Category4", "10000", "06/01/2020", "06/30/2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ( "Project5", "Category5", "10000", "06/01/2020", "06/30/2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ( "Project6", "Category6", "10000", "06/01/2020", "06/30/2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ( "Project7", "Category7", "10000", "06/01/2020", "06/30/2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ( "Project8", "Category8", "10000", "06/01/2020", "06/30/2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ( "Project9", "Category9", "10000", "06/01/2020", "06/30/2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ( "Project10", "Category10", "10000", "06/01/2020", "06/30/2020");

INSERT INTO pledges (amount, user_id, project_id) VALUES ( 250, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES ( 100, 13, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES ( 300, 2, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES ( 100, 3, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES ( 250, 5, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES ( 300, 6, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES ( 50, 6, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES ( 50, 13, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES ( 100, 2, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES ( 250, 5, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES ( 20, 5, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES ( 50, 8, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES ( 100, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES ( 250, 9, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES ( 100, 4, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES ( 300, 14, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES ( 100, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES ( 100, 2, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES ( 300, 6, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES ( 100, 3, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES ( 300, 7, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES ( 300, 7, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES ( 250, 5, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES ( 100, 1, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES ( 300, 3, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES ( 100, 9, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES ( 50, 9, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES ( 100, 14, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES ( 250, 7, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES ( 250, 1, 7);
